import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Crumble Web Page",
  description: "Generated by Basak Karadeniz",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Navbar></Navbar>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
